### ISSUE TITLE
Getting Started

### ISSUE THREAD

**Issue by alexoelkers** [alexoelkers/TMOLI#1]
ToDo:
- understand generation of robot .urdf files, what are they? Understand how the robot receives commands/actions. (Angel)  
- understand how to create a (robot) environment in gym_envs_urdf (Alex, Angel)
- understand how to extract information from the environment, ie. positions of obstacles etc (Alex, Angel)
- begin working on a path planning algorithm: 1) can you create an algorithm which takes an input from the env and returns a generic action (local collision avoidance). 2) can you create an algorithm which generates a global path plan (Filip)

MAIN GOAL: 
- Have a play around with the library!

**Comment by filipSand** [comment]
Having had a look around in the urdfenvs/urdf_common/ directory, there exists a bicycle_model.py class that I think we want to use. but it needs and .urdf file to actually be usable. I've also made a litlle script that can get the position of a robot. See the path_planner branch
